name: Deploy

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Setup SSH Key
        run: |
          echo "SHORT_COMMIT_ID=${{ github.sha:0:7 }}"
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          touch ~/.ssh/known_hosts
          ssh-keyscan -t rsa ${{ secrets.PRIVATE_SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Build
        run: |  
          make example_spider

      - name: Deploy to Private Server
        run: |
          scp -i ~/.ssh/id_rsa -r ./releases/example_spider ${{ secrets.PRIVATE_SERVER_USERNAME }}@${{ secrets.PRIVATE_SERVER_IP }}:${{ secrets.PRIVATE_SERVER_DIR }}
          scp -i ~/.ssh/id_rsa -r ./example.yml ${{ secrets.PRIVATE_SERVER_USERNAME }}@${{ secrets.PRIVATE_SERVER_IP }}:${{ secrets.PRIVATE_SERVER_DIR }}

      - name: Run
        run: |
          ssh ${{ secrets.PRIVATE_SERVER_USERNAME }}@${{ secrets.PRIVATE_SERVER_IP }} 'cd ${{ secrets.PRIVATE_SERVER_DIR }} && nohup ./example_spider -c example.yml > crawler.log &'
#          ssh ${{ secrets.PRIVATE_SERVER_USERNAME }}@${{ secrets.PRIVATE_SERVER_IP }} 'cd ${{ secrets.PRIVATE_SERVER_DIR }} && nohup ./example_spider -c example.yml > /dev/null 2>&1 &'